// <auto-generated />
using System;
using LasPisadas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LasPisadas.Migrations
{
    [DbContext(typeof(LasPisadasDbContext))]
    [Migration("20231124221243_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LasPisadas.Models.Zapato", b =>
                {
                    b.Property<int>("IdZapato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCorta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionDetallada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdZapato");

                    b.ToTable("Zapatos");
                });

            modelBuilder.Entity("LasPisadas.Models.ZapatoCategoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ZapatoIdZapato")
                        .HasColumnType("int");

                    b.HasKey("IdCategoria");

                    b.HasIndex("ZapatoIdZapato");

                    b.ToTable("ZapatoCategorias");
                });

            modelBuilder.Entity("LasPisadas.Models.ZapatoCategoria", b =>
                {
                    b.HasOne("LasPisadas.Models.Zapato", null)
                        .WithMany("CategoriasZapato")
                        .HasForeignKey("ZapatoIdZapato");
                });

            modelBuilder.Entity("LasPisadas.Models.Zapato", b =>
                {
                    b.Navigation("CategoriasZapato");
                });
#pragma warning restore 612, 618
        }
    }
}
